- backend/src/main/java/com/commitmate/re_cord/domain/post/category/entity/Category.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/entity/Comment.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/commentVote/entity/CommentVote.java
- backend/src/main/java/com/commitmate/re_cord/global/jpa/BaseEntity.java
- backend/src/main/java/com/commitmate/re_cord/global/jpa/UpdateStatus.java
- Comment Entity 생성
- Category Entity 생성
- baseEntity 변수명 변경 - ERD 참고
Closes #6
> feat:#6 comment, category entity

- backend/.gitignore
- backend/build.gradle.kts
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/DTO/CommentRequestDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/DTO/CommentResponseDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/repository/CommentRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/repository/PostRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/entity/Block.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/entity/User.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/repository/UserRepository.java
- backend/src/main/resources/application-secret.yml.default
- backend/src/main/resources/application.yml
Closes #25
- userid와 postid 받아와서 댓글 등록 할 수 있도록 함
> Feat #25 댓글 등록

- backend/.gitignore
- backend/build.gradle.kts
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/DTO/CommentRequestDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/DTO/CommentResponseDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/repository/CommentRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/repository/PostRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/entity/Block.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/entity/User.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/repository/UserRepository.java
- backend/src/main/resources/application-secret.yml.default
- backend/src/main/resources/application.yml
Closes #29
- 댓글을 삭제하면 db에서도 지우게끔 함
> [FEAT #29] MyBlog - 댓글 삭제

- backend/build.gradle.kts
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/entity/Block.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/controller/FollowController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/dto/FollowCountResponse.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/dto/FollowUserResponse.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/entity/Follow.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/repository/FollowRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/service/FollowService.java
- backend/src/main/resources/application-test.yml
- backend/src/test/java/com/commitmate/re_cord/domain/user/follow/service/FollowServiceTest.java
Closes #21
- 마이페이지>팔로우, 언팔로우 기능 추가
> [FEAT #21] MyPage - unfollow 기능

- backend/src/main/java/com/commitmate/re_cord/domain/user/block/controller/ApiV1BlockController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/repository/BlockRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/service/BlockService.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/controller/ApiV1FollowController.java
Closes #23  
- A 유저가 B 유저 차단
- FollowController -> ApiV1FollowController
> [FEAT #23] MyPage - Block 기능

- backend/src/main/java/com/commitmate/re_cord/domain/user/block/controller/ApiV1BlockController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/repository/BlockRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/service/BlockService.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/controller/ApiV1FollowController.java
- backend/src/main/java/com/commitmate/re_cord/global/exception/BlockNotFoundException.java
Closes #24
- 차단 해제 기능
- 차단 관계가 없는 경우 예외 발생
> [Feat #24] MyPage - Unblock 기능

- .github/workflows/gemini-code-review.yml
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/entity/Comment.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/commentVote/entity/CommentVote.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/commentVote/repository/CommentVoteRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/commentVote/service/CommentVoteService.java
Closes #45 
- 댓글 추천 기능 구현
- 한번 더 클릭할 시 추천 취소
> [FEAT #45] MyBlog-댓글 추천 기능 구현

- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/dto/CommentResponseDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/repository/CommentRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/global/config/SwaggerConfig.java
Closes #65
- 댓글 조회 기능 구현
- 로그인 하지 않은 사용자도 조회 가능
- 댓글은 페이징 처리
> [FEAT #65] MyBlog-댓글 조회 기능 구현

- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageCommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPagePostController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageUserController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPageUserService.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/UpdateUserDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/repository/UserRepository.java
- backend/src/main/resources/application.yml
Closes #67  
- mapping 주소 변경(/api)
- nickname 변경 건 -> username 변경
> [FEAT #67] userid 주입 변경 및 nickname 제거

- backend/src/main/java/com/commitmate/re_cord/domain/user/block/controller/ApiV1BlockController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/entity/Block.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/repository/BlockRepository.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/block/service/BlockService.java
- backend/src/main/java/com/commitmate/re_cord/global/exception/BlockNotFoundException.java
> [FEAT #26] MyPage - Block List 기능

- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPageUserService.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1UserController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/repository/UserRepository.java
- backend/src/main/java/com/commitmate/re_cord/global/security/SecurityConfig.java
- backend/src/main/java/com/commitmate/re_cord/global/security/handler/CustomOAuth2AuthenticationSuccessHandler.java
- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2ExceptionHandler.java
- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2FailureHandler.java
Closes # 71
- 액세스 토큰 중복 발급 수정
- 로그아웃 시 쿠키 삭제
> [FIX] MyPage - 소셜 로그인 액세스 토큰 중복 발급 수정

- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageCommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPagePostController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPageCommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPagePostService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostUpdateController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/dto/PostDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/service/PostService.java
Closes #85
- 어노테이션 등 추가해 comment  swagger 테스트 
- Swagger test 
- AI comment
> [FIX] MyPage - comment swagger 오류 수정

- backend/build.gradle.kts
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageCommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPagePostController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageUserController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostCreateController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostDeleteController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostReadController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostUpdateController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/controller/ApiV1FollowController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1OAuth2SignupController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1UserController.java
Closes FIX/#87
- 컨트롤러에 Operation 어노테이션 적용
> [FIX #87]: 컨트롤러에 Operation 어노테이션 적용

- backend/src/main/java/com/commitmate/re_cord/domain/user/user/service/AuthTokenService.java
- backend/src/main/java/com/commitmate/re_cord/global/Ut/Ut.java
> [FIX] Ut 패키지 경로 변경

- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/service/AuthTokenService.java
- backend/src/main/java/com/commitmate/re_cord/global/ut/Ut.java
> [REFACTOR] MyBlog - 댓글  URL 변경

- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageCommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPagePostController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/controller/ApiV1MyPageUserController.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPageCommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPagePostService.java
Closes #91 
- RESTful하게 API 주소 변경 완료
- 단순 데이터 조회 로직에는 @Transactional(readOnly = true) 적용
> [FIX] MyPage-API 주소 변경

- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPageCommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/mypage/service/MyPagePostService.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1UserController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/UserDto.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/service/UserService.java
- backend/src/main/java/com/commitmate/re_cord/global/security/SecurityConfig.java
- backend/src/main/resources/application.yml
Closes # 89
- api/me 로 헤더에서 요청을 계속 보내면서 로그인 상태 유지
> [FEAT] MyPage - 로그인: 프론트 헤더 -> api me 로그인 상태유지

- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/controller/ApiV1CommentController.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/dto/CommentResponseDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/comment/service/CommentService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/comment/commentVote/service/CommentVoteService.java
Closes #116 
- 추천 기능 구현(한번 더 클릭 시 취소)
- 댓글 총 개수 나타나도록 수정
> [FEAT #116] 댓글추천 및 총댓글 수 구현

- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1OAuth2SignupController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/ApiV1UserController.java
- frontend/src/app/signup/oauth2/page.tsx
- frontend/src/app/signup/page.tsx
Closes # 131
- 유저 탈퇴 시 로그아웃 상태유지
> 유저 탈퇴 시 로그아웃 상태유지

- backend/src/main/java/com/commitmate/re_cord/domain/post/post/repository/PostRepository.java
- frontend/src/app/mypage/components/MonthlyViewsChart.tsx
- frontend/src/app/mypage/components/PopularComments.tsx
- frontend/src/app/mypage/components/PopularPosts.tsx
- frontend/src/app/mypage/page.tsx
- frontend/src/app/mypage/statistics/comments/page.tsx
- frontend/src/app/mypage/statistics/page.tsx
- frontend/src/app/mypage/statistics/posts/page.tsx
- frontend/src/app/types/comment.ts
- frontend/src/app/types/post.ts
Closes #118  
- 총 글, 총 댓글, 총 조회수 일람
- 월별 조회수 그래프
- 추천 TOP5
> [FEAT #118] MyPage-Frontend-통계 메인 페이지 작업

- frontend/src/app/mypage/components/ProfileSidebar.tsx
- frontend/src/app/mypage/layout.tsx
Closes #145  
- SideBar에 username, info, profileImage를 연결
- layout에 적용함
> [FEAT #145] MyPage-SideBar API 연결

- backend/src/main/java/com/commitmate/re_cord/domain/user/user/controller/TempTokenController.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/OAuth2SignupRequest.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/SignupDto.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/UpdateUserDTO.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/dto/UserDto.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/entity/User.java
- backend/src/main/java/com/commitmate/re_cord/domain/user/user/service/UserService.java
- backend/src/main/java/com/commitmate/re_cord/global/exception/exceptions/OAuth2AdditionalInfoRequiredException.java
- backend/src/main/java/com/commitmate/re_cord/global/security/CustomOAuth2UserService.java
- backend/src/main/java/com/commitmate/re_cord/global/security/SecurityConfig.java
- backend/src/main/java/com/commitmate/re_cord/global/security/TempTokenProvider.java
- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2ExceptionHandler.java
- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2FailureHandler.java
- frontend/src/app/login/page.tsx
- frontend/src/app/signup/oauth2/page.tsx
- frontend/src/app/signup/page.tsx
Closes # 160
- 부트캠프 드롭다운
- 과정/기수로  변경
- generation int -> String으로 변경
- 추가 정보 입력시 oauthId, email 토큰으로 넘기는 것으로 변경
> [Feat #160] 부트캠프 드롭다운, 과정/기수로  변경

- backend/src/main/java/com/commitmate/re_cord/domain/home/controller/ApiV1HomeController.java
- backend/src/main/java/com/commitmate/re_cord/domain/home/service/HomeService.java
- backend/src/main/java/com/commitmate/re_cord/domain/post/post/repository/PostRepository.java
- backend/src/main/resources/application.yml
- frontend/src/app/home/page.tsx
- frontend/src/components/home/BootcampPopularPosts.tsx
- frontend/src/components/layout/Header.tsx
Closes #181 
- HeroSection사진 더 어둡게
- 부캠 별 인기 게시물 Published인것만 필터링
- 시작버튼 누르면 내 블로그 홈으로
> [FIX #181] 홈화면 자잘한 수정

- frontend/src/app/Blog/hooks/useLatestPost.ts
- frontend/src/app/ClientLayout.tsx
- frontend/src/app/api/like.ts
- frontend/src/app/api/search.ts
- frontend/src/app/login/page.tsx
- frontend/src/app/mypage/layout.tsx
- frontend/src/app/mypage/profile/page.tsx
- frontend/src/app/post/allPostList/components/PostContent.tsx
- frontend/src/app/post/allPostList/hooks/usePosts.ts
- frontend/src/app/post/allPostList/page.tsx
- frontend/src/app/post/categoryList/page.tsx
- frontend/src/app/signup/oauth2/page.tsx
- frontend/src/app/signup/page.tsx
- frontend/src/app/stores/auth/loginUser.tsx
- frontend/src/app/withdraw/page.tsx
- frontend/src/components/comment/commentSection.tsx
- frontend/src/components/home/BootcampPopularPosts.tsx
- frontend/src/components/home/RecentPosts.tsx
- frontend/src/components/home/WeeklyPopularPosts.tsx
- frontend/src/components/post/AuthorProfile.tsx
Closes # 178
-  백엔드 url 하드 코딩 -> base url로 변경
> [FIX] 백엔드 url 하드 코딩 -> base url로 변경

- frontend/src/app/login/page.tsx
> 로그인 - 로고 추가

- frontend/src/app/mypage/blocked/page.tsx
- frontend/src/components/block/blockList.tsx
- frontend/src/components/home/WeeklyPopularPosts.tsx
- frontend/src/components/post/AuthorProfile.tsx
- frontend/src/components/post/Statistics.tsx
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> [FIX] AuthorProfile 오류

- backend/src/main/resources/application.yml
- frontend/src/app/mypage/profile/page.tsx
- frontend/src/app/page.tsx
- frontend/src/components/post/CategoryMenu.tsx
- 마이페이지 부트캠프 드롭다운리스트 추가
- 자잘한 버튼색 수정
- 이름-> 닉네임 으로 변경
- 소속->부트캠프 로 변경
- 이메일 수정할 수 없도록 처리
> fix:마이페이지 프로필 및 버튼색 수정

- frontend/src/app/mypage/components/ProfileSidebar.tsx
> [FIX] 마이페이지 설정 삭제

- backend/src/main/java/com/commitmate/re_cord/domain/user/user/service/UserService.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> findByEmail 로그 ㅣㅉㄱ기

- backend/src/main/java/com/commitmate/re_cord/global/rq/Rq.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> Rq 에서 localhost 삭제

- backend/src/main/resources/application.yml
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> 카카오 로그인 하드코딩

- backend/src/main/resources/application.yml
Closes # 211
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> 카카오 깃허브 리다이렉트 uri 하드코딩

- backend/src/main/java/com/commitmate/re_cord/global/security/handler/CustomOAuth2AuthenticationSuccessHandler.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> fallback url 수정

- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2FailureHandler.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> Fix/#213 OAuth2Failurehandler url 하드코딩

- backend/src/main/java/com/commitmate/re_cord/global/security/handler/OAuth2FailureHandler.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> OAuth2FailureHandler url 수정

- frontend/.env.production
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> front base url 수정

- backend/src/main/resources/application.yml
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> [FIX #216]  깃허브 리디렉션 url 변경 테스트

- backend/src/main/resources/application.yml
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> url 변경 테스트

- backend/src/main/java/com/commitmate/re_cord/domain/post/post/controller/ApiV1PostReadController.java
- frontend/src/app/mypage/blocked/page.tsx
- frontend/src/app/post/postDetail/[userId]/[postId]/page.tsx
- frontend/src/components/block/blockList.tsx
- frontend/src/components/post/Statistics.tsx
Closes # 
- 나를 차단한 사람의 게시물을 조회 시 403 프론트 보완
> [Fix] 차단하기 포스트 차단 예외 처리 보완

- frontend/src/app/ClientLayout.tsx
- frontend/src/app/login/page.tsx
- frontend/src/app/signup/oauth2/page.tsx
Closes # 219
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> [FIX #219] 로그인/회원가입 로깅 수정

- backend/src/main/java/com/commitmate/re_cord/global/config/S3Service.java
Closes # 
- 변경된 내용/기능 요약
- 변경된 내용/기능 요약
> Feature/#301 키 변경

- backend/src/main/java/com/commitmate/re_cord/domain/user/follow/dto/FollowUserResponseDto.java
- frontend/src/app/mypage/followers/page.tsx
- frontend/src/app/mypage/following/page.tsx
- frontend/src/components/post/AuthorProfile.tsx
Closes # 
- 팔로우, 팔로잉 스위칭
- 팔로우, 팔로잉 스위칭
> [FIX] 마이페이지 - 팔로우 팔로잉 스위칭 follow following switching
